AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  kandidat13

  Sample SAM Template for kandidat13

Resources:
  ImageGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: generate_image_lambda.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.12
      Timeout: 60
      MemorySize: 1024
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: "pgr301-couch-explorers"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post

  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource: "arn:aws:s3:::pgr301-couch-explorers/13/generated_images/*"
              - Effect: Allow
                Action:
                  - "bedrock:InvokeService"
                  - "bedrock:InvokeModel"
                Resource: "*"

Outputs:
  GenerateImageURL:
    Description: "API gateway to image-generation url"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image/"
