name: Build, Push and Run Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest . 
        

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest 
        
        

    - name: Run Docker container with environment variables
      run: |
        docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                   -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                   -e SQS_QUEUE_URL="https://sqs.eu-west-1.amazonaws.com/244530008913/image_processing_queue_13" \
                   ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest "The most beautiful cat in the word"