name: Terraform Deploy

on:
  push:
    branches:
      - main
      - '*'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      TF_VAR_bucket_name: pgr301-couch-explorers

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      working-directory: ./infra
      run: terraform init

    - name: Validate Terraform
      working-directory: ./infra
      run: terraform validate

    - name: Terraform Plan
      if: github.ref != 'refs/heads/main'
      working-directory: ./infra
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ./infra
      run: terraform apply -auto-approve
